-- generated by harness/install-anim.py --helper-frames: the install walkthrough frames the helper window plays
-- (media/ui/pzopt_install/<os>/pzopt_install_<os>_NN.png, hold time in ms)
PZOptInstallFrames = {
    win = {
        { "media/ui/pzopt_install/win/pzopt_install_win_01.png", 700 },
        { "media/ui/pzopt_install/win/pzopt_install_win_02.png", 600 },
        { "media/ui/pzopt_install/win/pzopt_install_win_03.png", 1100 },
        { "media/ui/pzopt_install/win/pzopt_install_win_04.png", 1000 },
        { "media/ui/pzopt_install/win/pzopt_install_win_05.png", 1800 },
        { "media/ui/pzopt_install/win/pzopt_install_win_06.png", 1300 },
        { "media/ui/pzopt_install/win/pzopt_install_win_07.png", 2200 },
        { "media/ui/pzopt_install/win/pzopt_install_win_08.png", 2400 },
    },
    linux = {
        { "media/ui/pzopt_install/linux/pzopt_install_linux_01.png", 700 },
        { "media/ui/pzopt_install/linux/pzopt_install_linux_02.png", 600 },
        { "media/ui/pzopt_install/linux/pzopt_install_linux_03.png", 1100 },
        { "media/ui/pzopt_install/linux/pzopt_install_linux_04.png", 1000 },
        { "media/ui/pzopt_install/linux/pzopt_install_linux_05.png", 1800 },
        { "media/ui/pzopt_install/linux/pzopt_install_linux_06.png", 1300 },
        { "media/ui/pzopt_install/linux/pzopt_install_linux_07.png", 2200 },
        { "media/ui/pzopt_install/linux/pzopt_install_linux_08.png", 2400 },
    },
    mac = {
        { "media/ui/pzopt_install/mac/pzopt_install_mac_01.png", 700 },
        { "media/ui/pzopt_install/mac/pzopt_install_mac_02.png", 600 },
        { "media/ui/pzopt_install/mac/pzopt_install_mac_03.png", 1100 },
        { "media/ui/pzopt_install/mac/pzopt_install_mac_04.png", 1000 },
        { "media/ui/pzopt_install/mac/pzopt_install_mac_05.png", 1800 },
        { "media/ui/pzopt_install/mac/pzopt_install_mac_06.png", 1300 },
        { "media/ui/pzopt_install/mac/pzopt_install_mac_07.png", 2200 },
        { "media/ui/pzopt_install/mac/pzopt_install_mac_08.png", 2400 },
    },
}
