package pzopt;

/**
 * Generated by harness/godrays/door-glass.py from the game's tile art (Tiles2x.pack, newtiledefinitions.tiles): the glass of
 * every closed see-through door ("doorTrans" tiles, not garage doors or fence gates) as a band on its edge. God rays let
 * the light through that band of a closed door. Packed: along the edge from the square's NW corner (from, to), up the
 * level (from, to), 4 bits each in 1/15 steps.
 */
final class DoorGlass {
   private DoorGlass() {
   }

   private static final java.util.HashMap<String, Integer> BANDS = new java.util.HashMap<>();

   /** The packed band of a door sprite (u0 | u1 << 4 | h0 << 8 | h1 << 12), -1 when the art has none (a mod's door). */
   static int band(String sprite) {
      Integer b = sprite == null ? null : BANDS.get(sprite);
      return b == null ? -1 : b;
   }

   private static void put(String names, int... bands) {
      String[] n = names.split(" ");
      for (int i = 0; i < n.length; i++) {
         BANDS.put(n[i], bands[i]);
      }
   }

   static {
      put("fixtures_doors_01_108 fixtures_doors_01_109 fixtures_doors_01_116 fixtures_doors_01_117 fixtures_doors_01_16 fixtures_doors_01_17 fixtures_doors_01_20 fixtures_doors_01_21", 0xe1d2, 0xe0d1, 0xe1d2, 0xe0d1, 0xb8b4, 0xb8a4, 0xb8b4, 0xb8a4);
      put("fixtures_doors_01_32 fixtures_doors_01_33 fixtures_doors_01_36 fixtures_doors_01_37 fixtures_doors_01_40 fixtures_doors_01_41 fixtures_doors_01_44 fixtures_doors_01_45", 0xb1b4, 0xa1b4, 0xb1b4, 0xb1b3, 0xb1b4, 0xb1b3, 0xb6b4, 0xb6a4);
      put("fixtures_doors_01_48 fixtures_doors_01_49 fixtures_doors_01_60 fixtures_doors_01_61 fixtures_doors_02_4 fixtures_doors_02_40 fixtures_doors_02_41 fixtures_doors_02_44", 0xb1b4, 0xa1b3, 0xb8c9, 0xb8b8, 0xb6b4, 0xb1d5, 0xa1c5, 0xb192);
      put("fixtures_doors_02_45 fixtures_doors_02_5 fixtures_doors_02_56 fixtures_doors_02_57 fixtures_doors_02_60 fixtures_doors_02_61 location_restaurant_pileocrepe_01_48 location_restaurant_pileocrepe_01_49", 0xa192, 0xb6a4, 0xa7a8, 0xa7a7, 0xb764, 0xa763, 0xb6b4, 0xb6b3);
      put("location_restaurant_pizzawhirled_01_56 location_restaurant_pizzawhirled_01_57 location_restaurant_seahorse_01_48 location_restaurant_seahorse_01_49 location_restaurant_spiffos_01_48 location_restaurant_spiffos_01_49 location_shop_fossoil_01_60 location_shop_fossoil_01_61", 0xa1b4, 0xb1b4, 0xa1b4, 0xa1b3, 0xb1b4, 0xa1b3, 0xb1b4, 0xa1b3);
      put("location_shop_gas2go_01_60 location_shop_gas2go_01_61", 0xb1c4, 0xb1b3);
   }
}
