package pzopt;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.IdentityHashMap;
import org.joml.Vector3f;
import zombie.core.textures.Texture;
import zombie.iso.IsoChunk;
import zombie.iso.IsoDirections;
import zombie.iso.IsoWorld;
import zombie.iso.fboRenderChunk.FBORenderChunk;
import zombie.iso.sprite.IsoSprite;
import zombie.iso.sprite.IsoSpriteManager;
import zombie.tileDepth.TileDepthTexture;
import zombie.tileDepth.TileDepthTextureManager;
import zombie.tileDepth.TileGeometryUtils;

/**
 * Depth textures that match the sprite for the tiles the game gives a shared generic box (issue #38, 2026-09-29;
 * `tileDepthFix`, auto / on / off).
 *
 * <p>tileDepthTextureAssignments.txt maps 88 "Floating" wall cabinets (fixtures_counters_01, the Sunstar motel's and the
 * trailer's) to fixtures_counters_01_16's depth texture: a box over the whole square from 1.8 to 2.4495 (the ceiling). Stock
 * only sorts with it; pixel light, ambient occlusion, sun shadows and reflections read the chunk textures' depth as the
 * surface itself, so the upper half of every cabinet lay on the ceiling plane (lit by the level above: a seam through the
 * doors) and its front a full square out from the wall (AO darkened the wall and the seams). Here each tile gets the boxes
 * harness/tiledepth/fit-boxes.py fitted to its sprite (against the wall behind the doors, 0.55 squares deep; a corner piece
 * as two boxes, an L), drawn with the game's own box depth (TileGeometryUtils). Where the boxes miss the stock box's
 * pixels (up to 3 % of a sprite's opaque pixels, anti-aliased edges) the stock depth stays, so the texture covers at most
 * the pixels the stock one does. No texel is nearer than a plane TOP_DROP under the ceiling (stock clamps to just under
 * it): on the ceiling plane pixel light gave the tops the light of the level above.
 *
 * <p>`tileDepthCanopies` (the store canopies, 2026-09-29): 32 straight canopies borrow flat boxes up to the ceiling and are
 * Translucent, so the stock shader writes the box's depth on its transparent texels too (the air under the canopy: a dark
 * patch on the pavement under AO and pixel light). harness/tiledepth/fit-canopies.py fits a slab sloping down from the wall
 * plus the valance (rotated boxes), and every fitted texture here leaves out the texels the sprite's alpha mask leaves
 * empty. `tileDepthCeiling` (the general alternative): every depth texture uploaded with its top rows clamped under the
 * ceiling like the fitted ones (TileDepthTexture.updateGPUTexture), no fitting.
 *
 * <p>auto swaps them in while a feature that reads the depth is on (pixelLight, ambientOcclusion, sunShadows, reflections)
 * and keeps the stock textures otherwise, so the plain game sorts exactly as stock. Applied after every stock assignment
 * walk (the depth-map loads' finish, SpriteWindow's re-walk, IsoWorld's tile definitions) and on a live switch from the
 * Enhancements tab (then every loaded chunk texture bakes again). A tile whose assignment no longer points at the recorded
 * source (a game update, a mod) keeps whatever the game gave it.
 */
public final class TileDepthFix {
   private TileDepthFix() {
   }

   // generated by harness/tiledepth/fit-boxes.py: tile|source tile|the source's own box|fitted boxes, ';' between boxes;
   // a box is min x y z max x y z, or centre x y z, rotation x y z (degrees), min x y z, max x y z (TileGeometryUtils' space)
   static final String[] BOXES = {
      "fixtures_counters_01_16|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "fixtures_counters_01_17|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "fixtures_counters_01_18|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "fixtures_counters_01_19|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "fixtures_counters_01_20|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "fixtures_counters_01_21|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "fixtures_counters_01_22|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "fixtures_counters_01_23|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "fixtures_counters_01_24|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "fixtures_counters_01_25|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "fixtures_counters_01_26|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "fixtures_counters_01_27|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "fixtures_counters_01_28|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "fixtures_counters_01_29|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "fixtures_counters_01_30|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "fixtures_counters_01_31|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "fixtures_counters_01_144|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "fixtures_counters_01_145|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "fixtures_counters_01_146|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "fixtures_counters_01_147|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "fixtures_counters_01_148|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "fixtures_counters_01_149|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "fixtures_counters_01_150|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "fixtures_counters_01_151|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "fixtures_counters_01_152|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "fixtures_counters_01_153|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "fixtures_counters_01_154|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "fixtures_counters_01_155|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "fixtures_counters_01_156|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "fixtures_counters_01_157|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "fixtures_counters_01_158|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "fixtures_counters_01_159|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "fixtures_counters_01_160|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "fixtures_counters_01_161|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.425;-0.425 1.8 -0.5 0.1 2.4495 0.5",
      "fixtures_counters_01_162|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "fixtures_counters_01_163|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "fixtures_counters_01_164|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "fixtures_counters_01_165|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.425;-0.425 1.8 -0.5 0.1 2.4495 0.5",
      "fixtures_counters_01_166|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "fixtures_counters_01_167|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "fixtures_counters_01_168|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "fixtures_counters_01_169|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.45;-0.45 1.8 -0.5 0.1 2.4495 0.5",
      "fixtures_counters_01_170|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "fixtures_counters_01_171|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "fixtures_counters_01_172|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "fixtures_counters_01_173|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.45;-0.45 1.8 -0.5 0.1 2.4495 0.5",
      "fixtures_counters_01_174|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "fixtures_counters_01_175|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "fixtures_counters_01_176|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "fixtures_counters_01_177|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.425;-0.425 1.8 -0.5 0.1 2.4495 0.5",
      "fixtures_counters_01_178|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "fixtures_counters_01_179|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "fixtures_counters_01_180|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "fixtures_counters_01_181|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.425;-0.425 1.8 -0.5 0.1 2.4495 0.5",
      "fixtures_counters_01_182|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "fixtures_counters_01_183|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "fixtures_counters_01_184|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "fixtures_counters_01_185|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.45;-0.45 1.8 -0.5 0.1 2.4495 0.5",
      "fixtures_counters_01_186|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "fixtures_counters_01_187|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "fixtures_counters_01_188|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "fixtures_counters_01_189|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.45;-0.45 1.8 -0.5 0.1 2.4495 0.5",
      "fixtures_counters_01_190|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "fixtures_counters_01_191|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "fixtures_counters_01_200|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "fixtures_counters_01_201|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "fixtures_counters_01_202|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "fixtures_counters_01_203|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "fixtures_counters_01_204|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "fixtures_counters_01_205|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.45;-0.45 1.8 -0.5 0.1 2.4495 0.5",
      "fixtures_counters_01_206|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "fixtures_counters_01_207|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "location_hospitality_sunstarmotel_02_44|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.075 1.8 -0.475 0.475 2.4495 0.5",
      "location_hospitality_sunstarmotel_02_45|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.075 0.5 2.4495 0.5",
      "location_hospitality_sunstarmotel_02_46|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125",
      "location_hospitality_sunstarmotel_02_47|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.825 -0.475 0.125 2.4495 0.5",
      "location_hospitality_sunstarmotel_02_48|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.425 0.5 2.4495 0.15;-0.425 1.825 -0.5 0.15 2.4495 0.5",
      "location_hospitality_sunstarmotel_02_49|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.1 0.5 2.4495 0.45;-0.45 1.8 -0.5 0.1 2.4495 0.5",
      "location_hospitality_sunstarmotel_02_50|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.825 -0.075 0.5 2.4495 0.475;-0.075 1.825 -0.5 0.475 2.4495 0.5",
      "location_hospitality_sunstarmotel_02_51|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.425 0.5 2.4495 0.125;-0.125 1.8 -0.5 0.425 2.4495 0.5",
      "location_trailer_02_22|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.475 1.825 -0.425 0.5 2.4495 0.05",
      "location_trailer_02_23|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.8 -0.45 0.025 2.4495 0.5",
      "location_trailer_02_62|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.45 1.775 0.025 0.5 2.4495 0.475",
      "location_trailer_02_63|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|0 1.8 -0.475 0.45 2.4495 0.5",
      "location_trailer_02_68|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 0.025 0.5 2.4495 0.45;0.025 1.8 -0.5 0.45 2.4495 0.5",
      "location_trailer_02_69|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.775 0 0.5 2.4495 0.475;-0.475 1.775 -0.5 0 2.4495 0.5",
      "location_trailer_02_70|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.45 0.5 2.4495 0;-0.45 1.8 -0.5 0 2.4495 0.5",
      "location_trailer_02_71|fixtures_counters_01_16|-0.5 1.8 -0.5 0.5 2.4495 0.5|-0.5 1.8 -0.45 0.5 2.4495 0.025;-0.025 1.8 -0.5 0.45 2.4495 0.5",
   };

   // generated by harness/tiledepth/fit-canopies.py (tileDepthCanopies): straight canopies as a sloped slab and its valance,
   // domes as the outward half of an ellipsoid on the wall line (e centre, radii, wall axis, outward sign, wall coordinate, lowest y)
   static final String[] CANOPIES = {
      "location_restaurant_bar_smutz_12|walls_decoration_01_68|0 0 0 0 0 0 -0.5 2.05 -0.45 0.5 2.4495 0.05|0 2.3495 -0.25 26.5651 0 0 -0.5 -0.015 -0.2236 0.5 0.015 0.2236;0 0 0 0 0 0 -0.5 2.0495 -0.08 0.5 2.2495 -0.05",
      "location_restaurant_bar_smutz_13|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|-0.3 2.3495 0 0 0 -26.5651 -0.2236 -0.015 -0.5 0.2236 0.015 0.5;0 0 0 0 0 0 -0.13 2.0495 -0.5 -0.1 2.2495 0.5",
      "location_restaurant_bar_smutz_14|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|-0.3 2.3495 0 0 0 -26.5651 -0.2236 -0.015 -0.5 0.2236 0.015 0.5;0 0 0 0 0 0 -0.13 2.0495 -0.5 -0.1 2.2495 0.5",
      "location_restaurant_bar_smutz_15|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|-0.3 2.3495 0 0 0 -26.5651 -0.2236 -0.015 -0.5 0.2236 0.015 0.5;0 0 0 0 0 0 -0.13 2.0495 -0.5 -0.1 2.2495 0.5",
      "location_restaurant_pie_01_5|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|e -0.5 2 0 0.4 0.45 0.75 0 1 -0.5 2",
      "location_restaurant_pileocrepe_01_5|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|e -0.5 2 0 0.4 0.45 0.75 0 1 -0.5 2",
      "walls_decoration_01_68|walls_decoration_01_68|0 0 0 0 0 0 -0.5 2.05 -0.45 0.5 2.4495 0.05|0 2.3495 -0.25 26.5651 0 0 -0.5 -0.015 -0.2236 0.5 0.015 0.2236;0 0 0 0 0 0 -0.5 2.0495 -0.08 0.5 2.2495 -0.05",
      "walls_decoration_01_69|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|-0.3 2.3495 0 0 0 -26.5651 -0.2236 -0.015 -0.5 0.2236 0.015 0.5;0 0 0 0 0 0 -0.13 2.0495 -0.5 -0.1 2.2495 0.5",
      "walls_decoration_01_70|walls_decoration_01_68|0 0 0 0 0 0 -0.5 2.05 -0.45 0.5 2.4495 0.05|0 2.3495 -0.25 26.5651 0 0 -0.5 -0.015 -0.2236 0.5 0.015 0.2236;0 0 0 0 0 0 -0.5 2.0495 -0.08 0.5 2.2495 -0.05",
      "walls_decoration_01_71|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|-0.3 2.3495 0 0 0 -26.5651 -0.2236 -0.015 -0.5 0.2236 0.015 0.5;0 0 0 0 0 0 -0.13 2.0495 -0.5 -0.1 2.2495 0.5",
      "walls_decoration_01_84|walls_decoration_01_84|0 0 0 0 0 0 -0.5 1.75 -0.45 0.5 2.4495 0.5|0 2.2 0.05 21.8014 0 0 -0.5 -0.015 -0.5385 0.5 0.015 0.5385;0 0 0 0 0 0 -0.5 1.8 0.52 0.5 2 0.55",
      "walls_decoration_01_85|walls_decoration_01_85|0 0 0 0 0 0 -0.45 1.75 -0.5 0.5 2.4495 0.5|0 2.15 0 0 0 -26.5651 -0.559 -0.015 -0.5 0.559 0.015 0.5;0 0 0 0 0 0 0.47 1.8 -0.5 0.5 1.9 0.5",
      "walls_decoration_01_86|walls_decoration_01_86|0 0 0 0 0 0 -0.5 1.75 -0.5 0.5 2.4495 0.5|e -0.25 1.8 -0.5 0.75 0.45 1 2 1 -0.5 1.8",
      "walls_decoration_01_100|walls_decoration_01_84|0 0 0 0 0 0 -0.5 1.75 -0.45 0.5 2.4495 0.5|0 2.2 0.05 21.8014 0 0 -0.5 -0.015 -0.5385 0.5 0.015 0.5385;0 0 0 0 0 0 -0.5 1.8 0.52 0.5 2 0.55",
      "walls_decoration_01_101|walls_decoration_01_85|0 0 0 0 0 0 -0.45 1.75 -0.5 0.5 2.4495 0.5|0 2.15 0 0 0 -26.5651 -0.559 -0.015 -0.5 0.559 0.015 0.5;0 0 0 0 0 0 0.47 1.8 -0.5 0.5 1.9 0.5",
      "walls_decoration_01_102|walls_decoration_01_86|0 0 0 0 0 0 -0.5 1.75 -0.5 0.5 2.4495 0.5|e -0.25 1.8 -0.5 0.75 0.45 1 2 1 -0.5 1.8",
      "walls_decoration_01_112|walls_decoration_01_68|0 0 0 0 0 0 -0.5 2.05 -0.45 0.5 2.4495 0.05|0 2.3495 -0.25 26.5651 0 0 -0.5 -0.015 -0.2236 0.5 0.015 0.2236;0 0 0 0 0 0 -0.5 2.0495 -0.08 0.5 2.2495 -0.05",
      "walls_decoration_01_113|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|-0.25 2.2995 0 0 0 -36.8699 -0.25 -0.015 -0.5 0.25 0.015 0.5;0 0 0 0 0 0 -0.08 2.0495 -0.5 -0.05 2.1495 0.5",
      "walls_decoration_01_114|walls_decoration_01_68|0 0 0 0 0 0 -0.5 2.05 -0.45 0.5 2.4495 0.05|0 2.3495 -0.25 26.5651 0 0 -0.5 -0.015 -0.2236 0.5 0.015 0.2236;0 0 0 0 0 0 -0.5 2.0495 -0.08 0.5 2.2495 -0.05",
      "walls_decoration_01_115|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|-0.3 2.3495 0 0 0 -26.5651 -0.2236 -0.015 -0.5 0.2236 0.015 0.5;0 0 0 0 0 0 -0.13 2.0495 -0.5 -0.1 2.2495 0.5",
      "walls_decoration_01_116|walls_decoration_01_84|0 0 0 0 0 0 -0.5 1.75 -0.45 0.5 2.4495 0.5|0 2.2 0.05 21.8014 0 0 -0.5 -0.015 -0.5385 0.5 0.015 0.5385;0 0 0 0 0 0 -0.5 1.8 0.52 0.5 2 0.55",
      "walls_decoration_01_117|walls_decoration_01_85|0 0 0 0 0 0 -0.45 1.75 -0.5 0.5 2.4495 0.5|0 2.2 0 0 0 -21.8014 -0.5385 -0.015 -0.5 0.5385 0.015 0.5;0 0 0 0 0 0 0.47 1.8 -0.5 0.5 2 0.5",
      "walls_decoration_01_118|walls_decoration_01_86|0 0 0 0 0 0 -0.5 1.75 -0.5 0.5 2.4495 0.5|e -0.25 1.8 -0.5 0.75 0.45 1 2 1 -0.5 1.8",
      "walls_decoration_01_120|walls_decoration_01_68|0 0 0 0 0 0 -0.5 2.05 -0.45 0.5 2.4495 0.05|0 2.3495 -0.25 26.5651 0 0 -0.5 -0.015 -0.2236 0.5 0.015 0.2236;0 0 0 0 0 0 -0.5 2.0495 -0.08 0.5 2.2495 -0.05",
      "walls_decoration_01_121|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|-0.3 2.3495 0 0 0 -26.5651 -0.2236 -0.015 -0.5 0.2236 0.015 0.5;0 0 0 0 0 0 -0.13 2.0495 -0.5 -0.1 2.2495 0.5",
      "walls_decoration_01_122|walls_decoration_01_68|0 0 0 0 0 0 -0.5 2.05 -0.45 0.5 2.4495 0.05|0 2.3495 -0.25 26.5651 0 0 -0.5 -0.015 -0.2236 0.5 0.015 0.2236;0 0 0 0 0 0 -0.5 2.0495 -0.08 0.5 2.2495 -0.05",
      "walls_decoration_01_123|walls_decoration_01_69|0 0 0 0 0 0 -0.45 2.05 -0.5 0.05 2.4495 0.5|-0.25 2.2995 0 0 0 -36.8699 -0.25 -0.015 -0.5 0.25 0.015 0.5;0 0 0 0 0 0 -0.08 2.0495 -0.5 -0.05 2.1495 0.5",
      "walls_decoration_01_128|walls_decoration_01_84|0 0 0 0 0 0 -0.5 1.75 -0.45 0.5 2.4495 0.5|0 2.2 0.05 21.8014 0 0 -0.5 -0.015 -0.5385 0.5 0.015 0.5385;0 0 0 0 0 0 -0.5 1.8 0.52 0.5 2 0.55",
      "walls_decoration_01_129|walls_decoration_01_85|0 0 0 0 0 0 -0.45 1.75 -0.5 0.5 2.4495 0.5|0.05 2.15 0 0 0 -26.5651 -0.559 -0.015 -0.5 0.559 0.015 0.5;0 0 0 0 0 0 0.52 1.8 -0.5 0.55 1.9 0.5",
      "walls_decoration_01_130|walls_decoration_01_86|0 0 0 0 0 0 -0.5 1.75 -0.5 0.5 2.4495 0.5|e -0.25 1.8 -0.5 0.75 0.45 1 2 1 -0.5 1.8",
      "walls_decoration_01_132|walls_decoration_01_84|0 0 0 0 0 0 -0.5 1.75 -0.45 0.5 2.4495 0.5|0 2.2 0.025 22.8337 0 0 -0.5 -0.015 -0.5154 0.5 0.015 0.5154;0 0 0 0 0 0 -0.5 1.8 0.47 0.5 2 0.5",
      "walls_decoration_01_133|walls_decoration_01_85|0 0 0 0 0 0 -0.45 1.75 -0.5 0.5 2.4495 0.5|0.05 2.15 0 0 0 -26.5651 -0.559 -0.015 -0.5 0.559 0.015 0.5",
      "walls_decoration_01_144|walls_decoration_01_144|0 0 0 0 0 0 -0.5 1.5 -0.45 0.5 2.4495 0.5|0 2.1995 -0.025 30.4655 0 0 -0.5 -0.015 -0.4931 0.5 0.015 0.4931;0 0 0 0 0 0 -0.5 1.4495 0.37 0.5 1.9495 0.4",
      "walls_decoration_01_145|walls_decoration_01_145|0 0 0 0 0 0 -0.45 1.5 -0.5 0.5 2.4495 0.5|-0.05 2.1995 0 0 0 -32.0054 -0.4717 -0.015 -0.5 0.4717 0.015 0.5;0 0 0 0 0 0 0.32 1.4495 -0.5 0.35 1.9495 0.5",
      "walls_decoration_01_146|walls_decoration_01_146|0 0 0 0 0 0 -0.5 1.5 -0.5 0.5 2.4495 0.5|e -0.25 1.8 -0.5 0.5 0.6 1 2 1 -0.5 1.2",
      "walls_decoration_01_152|walls_decoration_01_144|0 0 0 0 0 0 -0.5 1.5 -0.45 0.5 2.4495 0.5|0 2.1995 -0.025 30.4655 0 0 -0.5 -0.015 -0.4931 0.5 0.015 0.4931;0 0 0 0 0 0 -0.5 1.4495 0.37 0.5 1.9495 0.4",
      "walls_decoration_01_153|walls_decoration_01_145|0 0 0 0 0 0 -0.45 1.5 -0.5 0.5 2.4495 0.5|-0.05 2.1995 0 0 0 -32.0054 -0.4717 -0.015 -0.5 0.4717 0.015 0.5;0 0 0 0 0 0 0.32 1.4495 -0.5 0.35 1.9495 0.5",
      "walls_decoration_01_154|walls_decoration_01_146|0 0 0 0 0 0 -0.5 1.5 -0.5 0.5 2.4495 0.5|e -0.25 1.8 -0.5 0.5 0.6 1 2 1 -0.5 1.2",
      "walls_decoration_01_160|walls_decoration_01_144|0 0 0 0 0 0 -0.5 1.5 -0.45 0.5 2.4495 0.5|0 2.1995 -0.025 30.4655 0 0 -0.5 -0.015 -0.4931 0.5 0.015 0.4931;0 0 0 0 0 0 -0.5 1.4495 0.37 0.5 1.9495 0.4",
      "walls_decoration_01_161|walls_decoration_01_145|0 0 0 0 0 0 -0.45 1.5 -0.5 0.5 2.4495 0.5|-0.05 2.1995 0 0 0 -32.0054 -0.4717 -0.015 -0.5 0.4717 0.015 0.5;0 0 0 0 0 0 0.32 1.4495 -0.5 0.35 1.9495 0.5",
      "walls_decoration_01_162|walls_decoration_01_146|0 0 0 0 0 0 -0.5 1.5 -0.5 0.5 2.4495 0.5|e -0.25 1.8 -0.5 0.5 0.6 1 2 1 -0.5 1.2",
   };

   private static final Vector3f ZERO = new Vector3f();
   static final float CEILING = 2.4495F; // a level's height in box units: the tops of the boxes
   // no texel is nearer than this far under the ceiling (the stock upper-floor clamp, deeper): pixel light takes a texel
   // within 0.006 levels under a level for that level and then the brighter of it and the one below (PixelLight: meant for
   // a wall's top row), so a cabinet top on the ceiling plane, and the top rows of its front, were lit by the roof or the
   // room upstairs (a pale top and a bright line in a dark kitchen). 0.04 units = 0.016 levels, ~7 steps of the 8-bit
   // depth; more made the wall behind rise above the tops and ambient occlusion smudged them (0.1 tried)
   static final float TOP_DROP = 0.04F;
   private static final int CEILING_ROWS = 68; // the rows (of 256) the plane under the ceiling crosses inside a tile, stock's 64 + the drop

   private static boolean built;
   private static final ArrayList<IsoSprite> sprites = new ArrayList<>();
   private static final ArrayList<TileDepthTexture> sources = new ArrayList<>();
   private static final ArrayList<TileDepthTexture> fixed = new ArrayList<>();
   private static final IdentityHashMap<TileDepthTexture, Boolean> ours = new IdentityHashMap<>();

   static boolean wanted() {
      if (!Overrides.enabled()) {
         return false;
      }
      return switch (Config.TILE_DEPTH_FIX) {
         case "on" -> true;
         case "off" -> false;
         default -> Config.PIXEL_LIGHT || Config.AO || Config.SUN_SHADOWS || Config.SSR;
      };
   }

   /** tileDepthCeiling: every non-roof depth texture's top rows clamped under the ceiling at upload (decided at boot). */
   public static boolean ceilingClamp() {
      return Config.TILE_DEPTH_CEILING && wanted();
   }

   /** The depth of the plane TOP_DROP under the ceiling at a texel of a w x h tile depth texture (-1: below the rows it crosses). */
   public static float underCeiling(int x, int y, int w, int h) {
      float[] p = underCeiling(w, h);
      return y * 256 >= CEILING_ROWS * h ? -1.0F : p[x + y * w];
   }

   /**
    * After a stock walk assigned the depth textures (loader thread or main thread): the fitted textures where wanted, the
    * stock one elsewhere. Idempotent; returns how many sprites changed.
    */
   public static synchronized int reapply() {
      try {
         boolean want = wanted();
         if (!built) {
            if (!want) {
               return 0; // nothing swapped yet, nothing to put back
            }
            build();
         }
         int changed = 0;
         for (int i = 0; i < sprites.size(); i++) {
            IsoSprite s = sprites.get(i);
            TileDepthTexture now = s.depthTexture;
            if (want && now == sources.get(i)) {
               s.depthTexture = fixed.get(i);
               changed++;
            } else if (!want && now != null && now == fixed.get(i)) {
               s.depthTexture = sources.get(i);
               changed++;
            }
         }
         if (changed > 0) {
            Log.info("tileDepthFix: " + (want ? "fitted" : "stock") + " depth on " + changed + " sprites (tileDepthFix=" + Config.TILE_DEPTH_FIX + ")");
         }
         return changed;
      } catch (RuntimeException e) {
         Log.warn("tileDepthFix: " + e); // the stock textures stay
         return 0;
      }
   }

   /** Game thread: a key that decides wanted() changed on the Enhancements tab; re-bake what the swap touched. */
   static void sync() {
      if (wanted()) {
         prepare();
      }
      int changed = reapply();
      if (changed == 0) {
         return;
      }
      zombie.iso.IsoCell cell = IsoWorld.instance.currentCell;
      if (cell != null) {
         for (int p = 0; p < 4; p++) {
            zombie.iso.IsoChunkMap cm = cell.getChunkMap(p);
            if (cm == null || cm.ignore || cm.getChunks() == null) {
               continue;
            }
            for (IsoChunk c : cm.getChunks()) {
               if (c != null) {
                  c.getRenderLevels(p).invalidateAll(FBORenderChunk.DIRTY_OBJECT_MODIFY);
               }
            }
         }
      }
      Log.info("tileDepthFix: chunk textures bake again");
   }

   /**
    * Builds the textures on a live switch and waits until the render thread has uploaded them (its queue runs in order):
    * a chunk texture re-baked before the upload read a blank depth texture, the tile shader discarded every texel, and the
    * cabinets were missing from it until its next bake (seen on the first live test). At load nothing bakes before the
    * uploads run.
    */
   private static void prepare() {
      synchronized (TileDepthFix.class) {
         if (built) {
            return;
         }
         build();
      }
      if (!fixed.isEmpty()) {
         try {
            zombie.core.opengl.RenderThread.invokeOnRenderContext(() -> {
            });
         } catch (RuntimeException e) {
            Log.warn("tileDepthFix: waiting for the uploads: " + e);
         }
      }
   }

   private static void build() {
      TileDepthTextureManager mgr = TileDepthTextureManager.getInstance();
      if (!mgr.isLoadingFinished()) {
         return; // the stock walk after the last load comes back here
      }
      built = true;
      long t0 = System.nanoTime();
      int missing = 0, masked = 0, n = 0;
      TileDepthTexture any = mgr.getTextureFromTileName(BOXES[0].split("\\|")[1]);
      anyTileset = any == null ? null : any.getTileset();
      HashMap<String, float[]> stockBySpec = new HashMap<>();
      HashMap<String, TileDepthTexture> byKey = new HashMap<>(); // tiles with the same result share one texture, as the stock tiles share theirs
      ArrayList<String> rows = new ArrayList<>(java.util.Arrays.asList(BOXES));
      if (Config.TILE_DEPTH_CANOPIES) {
         rows.addAll(java.util.Arrays.asList(CANOPIES));
      }
      for (String row : rows) {
         String[] f = row.split("\\|");
         IsoSprite s = IsoSpriteManager.instance.namedMap.get(f[0]);
         boolean noSource = "-".equals(f[1]); // a canopy the game gives no depth texture (drawn with the default one)
         TileDepthTexture src = noSource ? null : mgr.getTextureFromTileName(f[1]);
         if (s == null || !noSource && (src == null || src.isEmpty()) || noSource && (s.depthTexture != null || anyTileset == null)) {
            missing++;
            continue;
         }
         int w = noSource ? 128 : src.getWidth(), h = noSource ? 256 : src.getHeight();
         // an OpaquePixelsOnly sprite (the cabinets) never writes depth where it is transparent: no mask, fewer textures
         boolean[] mask = (s.depthFlags & IsoSprite.SDF_OPAQUE_PIXELS_ONLY) != 0 ? null : spriteMask(s, w, h);
         if (mask != null) {
            masked++;
         } else if (noSource) {
            missing++; // no depth texture and no mask: nothing to say which texels it covers
            continue;
         }
         float[] stock;
         if (noSource) {
            stock = new float[w * h]; // the coverage is the sprite's own texels; no stock depth to fall back to or stay behind
            for (int i = 0; i < w * h; i++) {
               stock[i] = mask[i] ? NO_STOCK : -1.0F;
            }
         } else {
            stock = stockBySpec.computeIfAbsent(f[2] + "@" + w + "x" + h, k -> pixels(f[2], w, h, null, null));
         }
         String key = f[1] + "|" + f[3] + "|" + (mask == null ? "-" : Integer.toHexString(java.util.Arrays.hashCode(mask)));
         TileDepthTexture t = byKey.get(key);
         if (t == null) {
            t = texture(noSource ? anyTileset : src.getTileset(), pixels(f[3], w, h, stock, mask), w, h, n++);
            byKey.put(key, t);
            ours.put(t, Boolean.TRUE);
         }
         sprites.add(s);
         sources.add(src);
         fixed.add(t);
      }
      Log.info("tileDepthFix: " + ours.size() + " fitted depth textures for " + fixed.size() + " tiles (" + masked + " with a sprite mask"
            + (Config.TILE_DEPTH_CANOPIES ? ", canopies on" : "") + (missing > 0 ? ", " + missing + " tiles not loaded" : "") + ") in "
            + (System.nanoTime() - t0) / 1_000_000L + " ms");
   }

   /** The sprite's alpha mask on the depth texture's texels (null: none kept, the texture keeps every texel). */
   static boolean[] spriteMask(IsoSprite s, int w, int h) {
      Texture t = s.texture;
      if (t == null) {
         t = s.getTextureForCurrentFrame(IsoDirections.N);
      }
      if (t == null || t.getMask() == null || t.getWidthOrig() <= 0 || t.getHeightOrig() <= 0) {
         return null;
      }
      int fw = t.getWidthOrig(), fh = t.getHeightOrig();
      boolean[] m = new boolean[w * h];
      for (int y = 0; y < h; y++) {
         for (int x = 0; x < w; x++) {
            m[x + y * w] = t.isMaskSet(x * fw / w, y * fh / h);
         }
      }
      return m;
   }

   private static zombie.tileDepth.TilesetDepthTexture anyTileset; // the tileset a no-source canopy's texture is named under
   private static final float NO_STOCK = 1.0E9F; // a covered texel with no stock depth (a canopy without a depth texture)

   private static TileDepthTexture texture(zombie.tileDepth.TilesetDepthTexture tileset, float[] px, int w, int h, int n) {
      TileDepthTexture t = new TileDepthTexture(tileset, 10000 + n); // a name of its own: DEPTH_<tileset>_1000n
      for (int y = 0; y < h; y++) {
         for (int x = 0; x < w; x++) {
            if (px[x + y * w] >= 0.0F) {
               t.setPixel(x, y, px[x + y * w]);
            }
         }
      }
      t.pzoptFilled();
      t.updateGPUTexture();
      return t;
   }

   /** The cabinets' source box (fixtures_counters_01_16) as the game draws it, for the unit test. */
   static float[] stockPixels(int w, int h) {
      return pixels(BOXES[0].split("\\|")[2], w, h, null, null);
   }

   static float[] pixels(String boxes, int w, int h, float[] stock) {
      return pixels(boxes, w, h, stock, null);
   }

   /**
    * The nearest of the boxes on every texel (stock == null: the plain boxes, -1 where they miss). With a stock box: only
    * its texels, the stock depth where the boxes miss, none where the sprite mask is empty, never nearer than the plane
    * under the ceiling.
    */
   static float[] pixels(String boxes, int w, int h, float[] stock, boolean[] mask) {
      String[] parts = boxes.trim().split(";");
      int nb = parts.length;
      Vector3f[] c = new Vector3f[nb], r = new Vector3f[nb], mn = new Vector3f[nb], mx = new Vector3f[nb];
      float[][] ell = new float[nb][];
      for (int b = 0; b < nb; b++) {
         String[] v = parts[b].trim().split("\\s+");
         if ("e".equals(v[0])) { // ellipsoid: centre, radii, the wall's axis (0 = x, 2 = z), outward sign, wall coordinate, lowest y
            ell[b] = new float[10];
            for (int k = 0; k < 10; k++) {
               ell[b][k] = Float.parseFloat(v[k + 1]);
            }
            continue;
         }
         int o = v.length >= 12 ? 6 : 0;
         c[b] = o == 0 ? ZERO : new Vector3f(Float.parseFloat(v[0]), Float.parseFloat(v[1]), Float.parseFloat(v[2]));
         r[b] = o == 0 ? ZERO : new Vector3f(Float.parseFloat(v[3]), Float.parseFloat(v[4]), Float.parseFloat(v[5]));
         mn[b] = new Vector3f(Float.parseFloat(v[o]), Float.parseFloat(v[o + 1]), Float.parseFloat(v[o + 2]));
         mx[b] = new Vector3f(Float.parseFloat(v[o + 3]), Float.parseFloat(v[o + 4]), Float.parseFloat(v[o + 5]));
      }
      float[] under = stock == null ? null : underCeiling(w, h);
      float[] hit = new float[w * h];
      for (int i = 0; i < w * h; i++) {
         hit[i] = -1.0F;
         if (stock != null && (stock[i] < 0.0F || mask != null && !mask[i])) {
            continue;
         }
         for (int b = 0; b < nb; b++) {
            float d = ell[b] != null ? ellipsoidAt(i % w, i / w, w, h, ell[b]) : depthAt(i % w, i / w, w, h, c[b], r[b], mn[b], mx[b]);
            if (d >= 0.0F && (hit[i] < 0.0F || d < hit[i])) {
               hit[i] = d;
            }
         }
      }
      if (stock == null) {
         return hit;
      }
      float vstep = mask == null ? 0.0F : verticalStep(w, h);
      float[] px = new float[w * h];
      for (int i = 0; i < w * h; i++) {
         if (stock[i] < 0.0F || mask != null && !mask[i]) {
            px[i] = -1.0F;
            continue;
         }
         float d = hit[i];
         if (d < 0.0F && mask != null) {
            d = fill(hit, i % w, i / w, w, h, vstep, stock[i] == NO_STOCK ? 3 * FILL_NEAR : FILL_NEAR); // a sprite texel the fitted shape misses: its surface, not the stock box's
         }
         if (stock[i] == NO_STOCK) {
            d = d >= 0.0F ? d : 0.5F; // no stock depth: a texel far from every fitted one gets the tile's middle depth
         } else {
            // never nearer than the stock box (a canopy's valance hangs a hair past the square: the stock depth sorts
            // characters in front of it there)
            d = d >= 0.0F ? Math.max(d, stock[i]) : stock[i];
         }
         // nor than the plane under the ceiling (the tops sit on it, the top rows of a front join it)
         px[i] = Math.max(d, i / w * 256 < CEILING_ROWS * h ? under[i] : -1.0F);
      }
      return px;
   }

   private static final int FILL_DOWN = 24, FILL_NEAR = 6;

   /**
    * The depth of a sprite texel the fitted boxes miss (the scalloped ends of a canopy's valance, its anti-aliased edges),
    * from the fitted texels around it: the first one above it in its column within FILL_DOWN rows, continued down at a
    * vertical face's depth step (a valance hangs straight down), else the nearest within FILL_NEAR texels; -1 if none.
    * Falling back to the stock box there drew the scallops and the edge rows on the box's faces (dark tongues).
    */
   private static float fill(float[] hit, int x, int y, int w, int h, float vstep, int near) {
      for (int dy = 1; dy <= FILL_DOWN && y - dy >= 0; dy++) {
         float d = hit[x + (y - dy) * w];
         if (d >= 0.0F) {
            return d + dy * vstep;
         }
      }
      float best = -1.0F;
      int bestD = Integer.MAX_VALUE;
      for (int dy = -near; dy <= near; dy++) {
         for (int dx = -near; dx <= near; dx++) {
            int xx = x + dx, yy = y + dy, dd = dx * dx + dy * dy;
            if (xx < 0 || yy < 0 || xx >= w || yy >= h || dd >= bestD || dd > near * near) {
               continue;
            }
            float d = hit[xx + yy * w];
            if (d >= 0.0F) {
               best = d;
               bestD = dd;
            }
         }
      }
      return best;
   }

   private static float vstepCache = Float.NaN;

   /** How much the normalised depth grows per texel row down a vertical face (the same for every vertical face in this view). */
   private static synchronized float verticalStep(int w, int h) {
      if (Float.isNaN(vstepCache)) {
         Vector3f mn = new Vector3f(-0.5F, 0.0F, -0.5F), mx = new Vector3f(0.5F, CEILING, 0.5F);
         int x = w / 4, y0 = h * 150 / 256, y1 = h * 170 / 256; // the tall box's south-west face
         vstepCache = (depthAt(x, y1, w, h, ZERO, ZERO, mn, mx) - depthAt(x, y0, w, h, ZERO, ZERO, mn, mx)) / (y1 - y0);
      }
      return vstepCache;
   }

   private static float[] planeCache;

   /** The depth of the plane TOP_DROP under the ceiling on every texel (the same for every texture). */
   private static synchronized float[] underCeiling(int w, int h) {
      if (planeCache == null || planeCache.length != w * h) {
         Vector3f point = new Vector3f(0.0F, CEILING - TOP_DROP, 0.0F);
         float[] p = new float[w * h];
         for (int i = 0; i < w * h; i++) {
            p[i] = planeAt(i % w, i / w, w, h, point);
         }
         planeCache = p;
      }
      return planeCache;
   }

   /** The game's normalised depth of a horizontal plane at a texel's centre, as the stock upper-floor clamp computes it. */
   private static float planeAt(int x, int y, int w, int h, Vector3f point) {
      float ts = zombie.core.Core.tileScale;
      return TileGeometryUtils.getNormalizedDepthOnPlaneAt((x + 0.5F) * 64.0F * ts / w, (y + 0.5F) * 128.0F * ts / h, zombie.vehicles.UI3DScene.GridPlane.XZ, point);
   }

   private static final Vector3f UP = new Vector3f(0.0F, 1.0F, 0.0F);

   /**
    * An ellipsoid's depth at a texel (-1: the ray misses its kept part: the outward side of the wall, above the cut). The ray
    * comes from the game's own plane intersection (two horizontal planes), the depth from a plane through the hit point.
    */
   private static float ellipsoidAt(int x, int y, int w, int h, float[] e) {
      float ts = zombie.core.Core.tileScale;
      float tx = (x + 0.5F) * 64.0F * ts / w, ty = (y + 0.5F) * 128.0F * ts / h;
      Vector3f lo = new Vector3f(), hi = new Vector3f();
      if (TileGeometryUtils.getDepthOnPlaneAt(tx, ty, new Vector3f(0.0F, 0.0F, 0.0F), UP, lo) == 666.0F
            || TileGeometryUtils.getDepthOnPlaneAt(tx, ty, new Vector3f(0.0F, 1.0F, 0.0F), UP, hi) == 666.0F) {
         return -1.0F;
      }
      // from the higher point (nearer the camera) into the screen, in the ellipsoid's unit-sphere space
      float dx = lo.x - hi.x, dy = lo.y - hi.y, dz = lo.z - hi.z;
      float ox = (hi.x - e[0]) / e[3], oy = (hi.y - e[1]) / e[4], oz = (hi.z - e[2]) / e[5];
      float ux = dx / e[3], uy = dy / e[4], uz = dz / e[5];
      float a = ux * ux + uy * uy + uz * uz, b = 2.0F * (ox * ux + oy * uy + oz * uz), c = ox * ox + oy * oy + oz * oz - 1.0F;
      float disc = b * b - 4.0F * a * c;
      if (disc < 0.0F) {
         return -1.0F;
      }
      float sq = (float)Math.sqrt(disc);
      for (float t : new float[]{(-b - sq) / (2.0F * a), (-b + sq) / (2.0F * a)}) { // nearer first
         float px = hi.x + dx * t, py = hi.y + dy * t, pz = hi.z + dz * t;
         float along = e[6] < 1.0F ? px : pz;
         if ((along - e[8]) * e[7] >= -1.0E-6F && py >= e[9]) {
            return TileGeometryUtils.getNormalizedDepthOnPlaneAt(tx, ty, new Vector3f(px, py, pz), UP);
         }
      }
      return -1.0F;
   }

   /** The game's normalised box depth at a texel's centre (-1: the box misses it), independent of the tile scale. */
   private static float depthAt(int x, int y, int w, int h, Vector3f centre, Vector3f rotation, Vector3f min, Vector3f max) {
      float ts = zombie.core.Core.tileScale; // TileGeometryUtils takes tile pixels: x / (64 ts) spans 0..1, y / (128 ts) 0..2
      return TileGeometryUtils.getNormalizedDepthOnBoxAt((x + 0.5F) * 64.0F * ts / w, (y + 0.5F) * 128.0F * ts / h, centre, rotation, min, max);
   }
}
