#!/usr/bin/env python3
"""When each pzopt.Config key was first released, for the options tabs' "Sort by: Release date".

A key's commit is the first commit of src/pzopt/pzopt/Config.java that declares it (`bool|integer|string("key"`);
its release is the earliest release tag (`b42.*`, before 2026-09-29 `win-*`) containing that commit, dated by the tag. Keys in no release yet
(committed after the newest tag, or not committed at all) are left out: the tab files them under "New in this
version", which is what they are in the build being made (release.sh builds before it tags). Writes
src/lua/client/pzopt/pzopt_optimizations_dates.lua (a global table key -> "YYYY-MM-DD"). build.sh runs it; without
git or the history (a zip or a shallow copy) the committed file is left as it is.
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = "src/pzopt/pzopt/Config.java"
OUT = ROOT / "src/lua/client/pzopt/pzopt_optimizations_dates.lua"
DECL = re.compile(r'\b(?:bool|integer|string|aoStrength)\(\s*"(\w+)"')


def git(*args):
    return subprocess.run(["git", "-C", str(ROOT), *args], check=True, capture_output=True, text=True).stdout


def main():
    try:
        if git("rev-parse", "--is-shallow-repository").strip() == "true":
            raise RuntimeError("shallow clone")
        log = git("log", "--reverse", "--format=@@%H", "-U0", "-p", "--", CONFIG)
        tags = git("for-each-ref", "--sort=creatordate", "--format=%(creatordate:short) %(refname:short)",
                   "refs/tags/win-*", "refs/tags/b4[0-9].*").split("\n")
    except (OSError, subprocess.CalledProcessError, RuntimeError) as e:
        print("option-dates: no git history (%s), %s left as it is" % (e, OUT.relative_to(ROOT)))
        return
    current = {m.group(1) for m in DECL.finditer((ROOT / CONFIG).read_text())}
    first = {}  # key -> commit that first declared it
    commit = None
    for line in log.splitlines():
        if line.startswith("@@") and not line.startswith("@@ "):
            commit = line[2:]
        elif line.startswith("+") and not line.startswith("+++"):
            for m in DECL.finditer(line):
                first.setdefault(m.group(1), commit)
    pending = {c for k, c in first.items() if k in current}
    released = {}  # commit -> date of the first release holding it
    for row in tags:
        if not pending:
            break
        if not row:
            continue
        date, tag = row.split(" ", 1)
        held = set(git("rev-list", tag).split())
        for c in pending & held:
            released[c] = date
        pending -= held
    dates = {k: released[c] for k, c in first.items() if k in current and c in released}
    lines = [
        "-- Generated by scripts/option-dates.py (build.sh runs it): the date of the first release (release tag) holding",
        "-- each pzopt.Config key, for the options tabs' \"Sort by: Release date\". A key missing here is new in this",
        "-- version. Do not edit by hand.",
        "PzoptOptionDates = {",
    ]
    for key in sorted(dates, key=str.lower):
        lines.append('    %s = "%s",' % (key, dates[key]))
    lines += ["}", "return PzoptOptionDates", ""]
    text = "\n".join(lines)
    if not OUT.exists() or OUT.read_text() != text:
        OUT.write_text(text)
    print("option-dates: %d keys, %d released, %d new -> %s"
          % (len(current), len(dates), len(current) - len(dates), OUT.relative_to(ROOT)))
    if "-v" in sys.argv:
        print("  new: " + " ".join(sorted(current - set(dates), key=str.lower)))


if __name__ == "__main__":
    main()
