#!/usr/bin/env python3
"""The glass of every closed see-through door ("doorTrans" tiles: a window in the door, glass doors, sliding glass doors)
measured from the game's own art, as the Java table src/pzopt/pzopt/DoorGlass.java (god rays: the light volume through a
closed door is its glass, not the doorway).

A door sprite on a W edge spans the square's NW corner (frame px 64, floor y 192) to its SW corner (px 0, floor y 224);
on an N edge NW (64, 192) to NE (128, 224); a level is 192 px (2x tiles). The glass is the leaf's translucent texels
(alpha 60..230 with solid texels 2 away on every side; the frame and the leaf are opaque, the rim's anti-aliasing
is not glass). Per sprite: the glass's extent
along the edge (from the NW corner) and up the level, 2nd..98th percentile, in 1/15 steps (4 bits each).

    door-glass.py [--sheet /tmp/door-glass.png] [--out src/pzopt/pzopt/DoorGlass.java]
"""
import argparse
import importlib.util
import os

import numpy as np
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("fb", os.path.join(HERE, "..", "tiledepth", "fit-boxes.py"))
fb = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fb)


def band(img, west):
    a = np.asarray(img)[:, :, 3].astype(int)
    solid = a >= 60
    inner = np.zeros_like(solid)  # not the leaf's anti-aliased rim: solid 2 texels away on all four sides
    inner[2:-2, 2:-2] = solid[:-4, 2:-2] & solid[4:, 2:-2] & solid[2:-2, :-4] & solid[2:-2, 4:]
    ys, xs = np.nonzero((a >= 60) & (a <= 230) & inner)
    if len(xs) < 40:
        return None
    X = xs + 0.5
    Y = ys + 0.5
    u = (64.0 - X) / 64.0 if west else (X - 64.0) / 64.0
    floor = 192.0 + 32.0 * u
    h = (floor - Y) / 192.0
    ok = (u > -0.05) & (u < 1.05) & (h > -0.05) & (h < 1.05)
    u, h = u[ok], h[ok]
    if len(u) < 40:
        return None
    u0, u1 = np.percentile(u, 2), np.percentile(u, 98)
    h0, h1 = np.percentile(h, 2), np.percentile(h, 98)
    q = lambda v: int(min(15, max(0, round(v * 15))))
    return q(u0), q(u1), q(h0), q(h1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sheet", default="")
    ap.add_argument("--out", default=os.path.join(HERE, "..", "..", "src", "pzopt", "pzopt", "DoorGlass.java"))
    a = ap.parse_args()
    props = fb.read_tiledefs(os.path.join(fb.MEDIA, "newtiledefinitions.tiles"))
    want = {}
    for n, p in props.items():
        if "doorTrans" not in p or "GarageDoor" in p or n.startswith(("fixtures_doors_fences", "walls_logs")):
            continue
        if "doorW" in p or "doorN" in p:
            want[n] = "doorW" in p
    sprites = fb.read_pack(os.path.join(fb.MEDIA, "texturepacks", "Tiles2x.pack"), set(want))
    rows = []
    for n in sorted(want):
        if n not in sprites:
            continue
        b = band(sprites[n], want[n])
        if b is None or b[1] <= b[0] or b[3] <= b[2]:
            print(f"skip {n}: no glass found")
            continue
        rows.append((n, b))
    if a.sheet:
        cols = 12
        sheet = Image.new("RGBA", (128 * cols, 256 * ((len(rows) + cols - 1) // cols)), (40, 40, 40, 255))
        dr = ImageDraw.Draw(sheet)
        for i, (n, b) in enumerate(rows):
            ox, oy = (i % cols) * 128, (i // cols) * 256
            sheet.paste(sprites[n], (ox, oy), sprites[n])
            w = want[n]
            pts = []
            for (u, hh) in ((b[0], b[2]), (b[1], b[2]), (b[1], b[3]), (b[0], b[3])):
                u, hh = u / 15.0, hh / 15.0
                x = 64 - 64 * u if w else 64 + 64 * u
                y = 192 + 32 * u - 192 * hh
                pts.append((ox + x, oy + y))
            dr.polygon(pts, outline=(255, 255, 0, 255))
        sheet.save(a.sheet)
    with open(a.out, "w") as f:
        f.write("package pzopt;\n\n")
        f.write("/**\n * Generated by harness/godrays/door-glass.py from the game's tile art (Tiles2x.pack, newtiledefinitions.tiles): the glass of\n")
        f.write(" * every closed see-through door (\"doorTrans\" tiles, not garage doors or fence gates) as a band on its edge. God rays let\n")
        f.write(" * the light through that band of a closed door. Packed: along the edge from the square's NW corner (from, to), up the\n")
        f.write(" * level (from, to), 4 bits each in 1/15 steps.\n */\n")
        f.write("final class DoorGlass {\n   private DoorGlass() {\n   }\n\n")
        f.write("   private static final java.util.HashMap<String, Integer> BANDS = new java.util.HashMap<>();\n\n")
        f.write("   /** The packed band of a door sprite (u0 | u1 << 4 | h0 << 8 | h1 << 12), -1 when the art has none (a mod's door). */\n")
        f.write("   static int band(String sprite) {\n      Integer b = sprite == null ? null : BANDS.get(sprite);\n      return b == null ? -1 : b;\n   }\n\n")
        f.write("   private static void put(String names, int... bands) {\n      String[] n = names.split(\" \");\n")
        f.write("      for (int i = 0; i < n.length; i++) {\n         BANDS.put(n[i], bands[i]);\n      }\n   }\n\n")
        f.write("   static {\n")
        for i in range(0, len(rows), 8):
            chunk = rows[i:i + 8]
            names = " ".join(n for n, _ in chunk)
            vals = ", ".join("0x%04x" % (b[0] | b[1] << 4 | b[2] << 8 | b[3] << 12) for _, b in chunk)
            f.write(f"      put(\"{names}\", {vals});\n")
        f.write("   }\n}\n")
    print(f"{len(rows)} doors -> {a.out}")


if __name__ == "__main__":
    main()
